#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>

int checkP2(int x);
int *dTob(int n, int l);
int bTod(int a[], int l);

int main() {
    int pgs = 4; // page size
    int ms = 32; // memory size
    int nof = ms / pgs; // number of frames
    int offset_bit; // find out # of bits required for offset
    int m; // find out address spaces required in main memory
    int pg_num_bit; // find out # of bits required for page number
    int la[] = {8, 4, 3, 2, 15, 18, 25}; // logical addresses generated by the CPU
    int pmt[] = {3, 6, 8, 12, 2}; // page table
    
    offset_bit = checkP2(pgs); // calculate offset bits
    m = checkP2(ms); // calculate total bits for memory
    pg_num_bit = m - offset_bit; // calculate page number bits
    
    printf("Page size: %d\n", pgs);
    printf("Memory size: %d\n", ms);
    printf("Number of frames required: %d\n", nof);
    printf("Page number bits: %d\n", pg_num_bit);
    printf("Offset bits: %d\n", offset_bit);
    printf("Number of address spaces: %d\n", m);
    printf("Page Table_____\n");
    for (int i = 0; i < sizeof(pmt) / sizeof(pmt[0]); i++) {
        printf("%d -> %d\n", i, pmt[i]);
    }

    for (int i = 0; i < sizeof(la) / sizeof(la[0]); i++) {
        int logical_address = la[i];
        int page_number = logical_address >> offset_bit;
        int offset = logical_address & ((1 << offset_bit) - 1);
        if (page_number >= sizeof(pmt) / sizeof(pmt[0])) {
            printf("%d is an invalid page number\n", logical_address);
        } else {
            int frame_number = pmt[page_number];
            if (frame_number == -1) {
                printf("%d is an invalid page number\n", logical_address);
            } else {
                int physical_address = (frame_number * pgs) + offset;
                if (physical_address >= ms) {
                    printf("%d is an invalid physical address\n", logical_address);
                } else {
                    printf("Corresponding physical address of logical address %d: %d\n", logical_address, physical_address);
                }
            }
        }
    }

    return 0;
}

int checkP2(int x) {

    int count = 0;
    while (x > 1) {
        if (x % 2 != 0) {
            return -1; 
        }
        x /= 2;
        count++;
    }
    return count;
}

int *dTob(int n, int l) {
    int *binary_array = malloc(l * sizeof(int));
    int i;
    for (i = l - 1; i >= 0; i--) {
        binary_array[i] = n % 2;
        n /= 2;
    }
    return binary_array;
}

int bTod(int a[], int l) {
    int decimal = 0;
    int i;
    for (i = 0; i < l; i++) {
        decimal = decimal * 2 + a[i];
    }
    return decimal;
}
